version: '3'

services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: NestJS-Postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data