export enum SwaggerTags {
  Auth = 'Auth',
  Profile = 'Profile',
  Users = 'Users',
  Roles = 'Roles',
  Cloudinary = 'Cloudinary',
  Municipality = 'Municipality',
  Town = 'Town',
  Models = 'Models',
  Facilities = 'Facilities',
  Categories = 'Categories',
  Languages = 'Languages',
  Images = 'Images',
  Places = 'Places',
  Lodgings = 'Lodgings',
  Seeds = 'Seeds',
  Experiences = 'Experiences',
  Restaurants = 'Restaurants',
  Reviews = 'Reviews',
  PublicReviews = 'Public Reviews',
  Transport = 'Transport',
  ImageResources = 'Image Resources',
  Commerce = 'Commerce',
  Guides = 'Guides',
}
