export enum SwaggerTags {
  Auth = 'Auth',
  Profile = 'Profile',
  Users = 'Users',
  Roles = 'Roles',
  Cloudinary = 'Cloudinary',
  Municipality = 'Municipality',
  Town = 'Town',
  Models = 'Models',
  Facilities = 'Facilities',
  Categories = 'Categories',
  Languages = 'Languages',
  Images = 'Images',
  Places = 'Places',
}
