export const ContentTypes = {
  FORM_URLENCODED: 'application/x-www-form-urlencoded',
  MULTIPART_FORM_DATA: 'multipart/form-data',
  JSON: 'application/json',
  TEXT_PLAIN: 'text/plain',
  XML: 'application/xml',
  OCTET_STREAM: 'application/octet-stream',
  CSV: 'text/csv',
  HTML: 'text/html',
  JAVASCRIPT: 'application/javascript',
  CSS: 'text/css',
  PDF: 'application/pdf',
  ZIP: 'application/zip',
  PNG: 'image/png',
  JPEG: 'image/jpeg',
  GIF: 'image/gif',
  WEBP: 'image/webp',
  MP4: 'video/mp4',
  MP3: 'audio/mpeg',
};
