import type { SheetCommerceData } from '../interfaces';

export const SHEET_COMMERCE_HEADERS: Array<keyof SheetCommerceData> = [
  'checked',
  'name',
  'slug',
  'town',
  'address',
  'categories',
  'facilities',
  'phonesNumbers',
  'email',
  'website',
  'description',
  'openingHours',
  'howToGetThere',
  'zone',
  'distance',
  'driveFolder',
  'languages',
  'longitude',
  'latitude',
  'googleMaps',
  'whatsapps',
  'facebook',
  'instagram',
  'airbnb',
];
