import type { SheetRestaurantData } from '../interfaces';

export const SHEET_RESTAURANT_HEADERS: Array<keyof SheetRestaurantData> = [
  'checked',
  'town',
  'categories',
  'facilities',
  'name',
  'slug',
  'description',
  'points',
  'spokenLanguages',
  'address',
  'phoneNumbers',
  'whatsappNumbers',
  'openingHours',
  'email',
  'website',
  'instagram',
  'facebook',
  'lowestPrice',
  'highestPrice',
  'longitude',
  'latitude',
  'urbanCenterDistance',
  'googleMapsUrl',
  'howToGetThere',
  'townZone',
];
