import type { SheetLodgingData } from '../interfaces';

export const SHEET_LODGING_HEADERS: Array<keyof SheetLodgingData> = [
  'checked',
  'name',
  'slug',
  'town',
  'address',
  'categories',
  'facilities',
  'phones',
  'email',
  'website',
  'description',
  'openingHours',
  'availability',
  'howToGetThere',
  'zone',
  'distance',
  'maxCapacity',
  'roomTypes',
  'roomCount',
  'lowestPrice',
  'highestPrice',
  'conveniences',
  'commonAreas',
  'driveFolder',
  'languages',
  'longitude',
  'latitude',
  'googleMaps',
  'whatsapps',
  'facebook',
  'instagram',
  'airbnb',
  'amenities',
];
