import type { SheetPlaceData } from '../interfaces';

export const SHEET_PLACE_HEADERS: Array<keyof SheetPlaceData> = [
  'checked',
  'order',
  'name',
  'slug',
  'imageCount',
  'zone',
  'description',
  'longitude',
  'latitude',
  'googleMapsLink',
  'driveFolderLink',
  'cloudinaryFolder',
  'difficulty',
  'facilities',
  'points',
  'distance',
  'altitude',
  'howToGetThere',
  'town',
  'category',
  'arrivalReference',
  'transportReference',
  'maxDeep',
  'capacity',
  'minAge',
  'maxAge',
  'recomendations',
  'howToDress',
  'internalRecommendations',
  'temperature',
  'popularity',
];
