import type { SheetExperience } from '../interfaces';

export const SHEET_EXPERIENCE_HEADERS: Array<keyof SheetExperience> = [
  'id',
  'town',
  'categories',
  'facilities',
  'title',
  'slug',
  'description',
  'difficultyLevel',
  'price',
  'departureDescription',
  'departureLongitude',
  'departureLatitude',
  'arrivalDescription',
  'arrivalLongitude',
  'arrivalLatitude',
  'totalDistance',
  'travelTime',
  'points',
  'minAge',
  'maxAge',
  'minParticipants',
  'maxParticipants',
  'recommendations',
  'howToDress',
  'restrictions',
  'guides',
] as const;
